site_name: Atomic Lines

nav:
  - Intro: index.md
  - Code Reference: reference/

theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - navigation.sections
    - navigation.prune
    - navigation.instant
    - navigation.tracking
    #    - toc.integrate
    - toc.follow

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_toc_entry: False
            show_symbol_type_toc: True
  - offline

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - tables
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - css/code_select.css
